name: Pre-release PR

on:
  pull_request:
    branches:
      - "master"
    paths-ignore: # not always respected. See https://github.com/actions/runner/issues/2324#issuecomment-1703345084
      - ".github/**"
      - "**.md"

jobs:
  code_test:
    name: Python tests and checks
    uses: ./.github/workflows/sub_testing.yml

  preprod_test:
    name: Code testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Find spawn.sh script version
        run: egrep '^# Spawn Version:[0-9]+$' ./exegol/utils/imgsync/spawn.sh | cut -d ':' -f2

  build:
    name: Build Python 🐍 distributions
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user build
      - name: Cleaning
        run : python setup.py clean test
      - name: Build Exegol
        run: python -m build --sdist --outdir dist/ .
