name: Nightly build

on:
  push:
    branches:
      - "cicd"
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  testing:
    name: Code testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: false
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user mypy types-requests types-PyYAML
      - name: Run code analysis
        run: mypy ./exegol/ --ignore-missing-imports --check-untyped-defs --pretty # TODO add --disallow-untyped-defs
      - name: Check python compatibility for 3.7
        run: mypy ./exegol/ --ignore-missing-imports --check-untyped-defs --python-version 3.7
      - name: Check python compatibility for 3.8
        run: mypy ./exegol/ --ignore-missing-imports --check-untyped-defs --python-version 3.8
      - name: Check python compatibility for 3.9
        run: mypy ./exegol/ --ignore-missing-imports --check-untyped-defs --python-version 3.9
      - name: Check python compatibility for 3.10
        run: mypy ./exegol/ --ignore-missing-imports --check-untyped-defs --python-version 3.10
      - name: Check python compatibility for 3.11
        run: mypy ./exegol/ --ignore-missing-imports --check-untyped-defs --python-version 3.11
  build-n-publish:
    name: Build and publish Python 🐍 distributions to TestPyPI 📦
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install requirements
        run: python -m pip install --user build
      - name: Cleaning
        run : python setup.py clean
      - name: Build Exegol
        run: python -m build --sdist --outdir dist/ .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
